name: firestore_entity_gen
description: A source_gen-based generator to produce structured Firestore entity mappers for Flutter/Dart.
version: 0.0.2+1-pre

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.7.0
  http: ^1.5.0
  args: ^2.4.0
  build: ^2.4.1
  source_gen: ^1.2.2
  analyzer: ^5.12.0
  dart_style: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.0
  test: ^1.21.0
  
repository: https://github.com/mizou-co-jp/firestore_entity_gen


# builder configuration is provided in build.yaml
